### ISSUE TITLE
AccesDenied with new version

### ISSUE THREAD

**Issue by aleon68** [appleboy/lambda-action#15]
2020/10/24 03:39:22 AccessDeniedException: 
	status code: 403, request id: 88525d89-5162-461c-9df0-751443ef394b
2020/10/24 03:39:22 AccessDeniedException: 
	status code: 403, request id: 88525d89-5162-461c-9df0-751443ef394b

This issue without any change on template

**Comment by appleboy** [comment]
I will take it

**Comment by appleboy** [comment]
duplicate of https://github.com/appleboy/lambda-action/issues/14
