### ISSUE TITLE
AccessDenied last version

### ISSUE THREAD

**Issue by aleon68** [appleboy/lambda-action#18]
2020/10/25 00:44:49 AccessDeniedException: 
	status code: 403, request id: 3b0efa8d-e5b9-44d1-b5e9-4d8b4f7ab97c
2020/10/25 00:44:49 AccessDeniedException: 
	status code: 403, request id: 3b0efa8d-e5b9-44d1-b5e9-4d8b4f7ab97c

Previous version was fixed, but again have issue

**Comment by aleon68** [comment]
I have an update, AccessDeniedException only show when YML have handler key, work when delete this key

**Comment by appleboy** [comment]
@aleon68 Yes. You need more permission to update Lambda configuration.

**Comment by aleon68** [comment]
You have rigth, update IAM permission and work fine, thanks, only add lambda:UpdateFunctionConfiguration to user on IAM and problem solve.

Thanks a lot
