### ISSUE TITLE
Support for docker image

### ISSUE THREAD

**Issue by kyle-thedelta** [appleboy/lambda-action#20]
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by PhilippeFerreiraDeSousa** [comment]
I just had the use-case.
If somebody is looking for a quick alternative, updating the image to the tag latest and deploying should be :
```
aws lambda update-function-code --function-name example --image-uri 0123456789.dkr.ecr.us-east-2.amazonaws.com/example-image-name:latest --deploy
```
Need for the latest version of the aws cli 2.1.10

**Comment by kelvin-tran** [comment]
@PhilippeFerreiraDeSousa 

The awscli lambda `update-function-code` [command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-function-code.html) doesn't have a `--deploy` option. Do you mean `--publish` (which publishes a new version after updating the code)? Eg:
```
aws lambda update-function-code --function-name example --image-uri 0123456789.dkr.ecr.us-east-2.amazonaws.com/example-image-name:latest --publish
```
In any event, it works without the option, so thanks for the comment.

**Comment by appleboy** [comment]
I will take it. Thanks for your feedback.

**Comment by appleboy** [comment]
Please set the `image_uri`:

> URI of a container image in the Amazon ECR registry.

**Comment by dhaydenags** [comment]
for the image_uri can we set variables for the uri?

image_uri: $ECR_REGISTRY/$ECR_REPOSITORY:$TAG

returns 

Message_: "Source image $ECR_REGISTRY/$ECR_REPOSITORY:$TAG is not valid. Provide a valid source image.",
