### ISSUE TITLE
Feb 12 2021 lamba-action@master inserting DRONE_COMMIT and overwriting lambda ENV

### ISSUE THREAD

**Issue by scottdavidreynolds** [appleboy/lambda-action#22]
As of today our Lambda ENV is being overwritten by this line:

DRONE_COMMIT=<hash_of_github_action>

We see that the ENV setting has been added to lambda-action as of Feb 12th. This must be correlated. We do not specify ENV in our github actions workflow yaml files. These values are stored in the Lambda directly with KMS.

**Comment by scottdavidreynolds** [comment]
I have a forked version https://github.com/Meetiers/lambda-action that returns the server back to use 1.2.3 from October before there ENV functionality was added and now my deploys do not overwrite my lambda env.

**Comment by ryanhuff** [comment]
I'm seeing this as well. You're wiping out my environment variables.

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/lambda-action/releases/tag/v0.1.1
