### ISSUE TITLE
Change in behaviour when updating a lambda using this action

### ISSUE THREAD

**Issue by tiago-loureiro** [appleboy/lambda-action#25]
I have been using this action since the [october version](https://github.com/appleboy/lambda-action/commit/c56c1b2a379b675adaec781b5fbd202938a827e4) without any problems; however, a current change in the behaviour of this action has caused my deployments to suddenly fail.

I looked through the work done in the past days and there seems to be a behavioural change related to environment variables: this worked very well for me because I managed the rest of the environment with terraform, i.e., the env variables are managed separately.

Previously, it was not possible to set any environment variables and since [this version](https://github.com/appleboy/lambda-action/commit/9bb4b6817648db9a0fd415d47f58bca07dfb3adb) this seems to be possible; this is not really a problem (I think it's a great solution) the issue is that if I specify nothing as environment, the action overrides my variables and I end up with a single variable `DRONE_COMMIT`. Not sure that this [drone lambda commit](https://github.com/appleboy/drone-lambda/commit/cf678c689c530e063a63fd8891edb30b13ab7d15) commit is the culprit, my Go skills are not the best :)

What I'd like to know is:
 * Was it intentional to remove environment variables from the lambda if you set none? It is not clear to me looking at the PR descriptions.
 * If it was intentional, can we add another setting such as `removeOtherVariables: false` or similar? Or simply do not touch environment variables if nothing is set?

Thanks!

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
I will bump the new version.

**Comment by appleboy** [comment]
https://github.com/appleboy/lambda-action/releases/tag/v0.1.7
