### ISSUE TITLE
Clarify formats supported for FunctionName

### ISSUE THREAD

**Issue by maromatorio** [appleboy/lambda-action#3]
What formats does the Lambda Function Name support? Full ARN? Simple name?

**Comment by maromatorio** [comment]
Looks like it's working with just the function name, not sure if it supports full arn or not

**Comment by appleboy** [comment]
@maromatorio I will take it.

**Comment by appleboy** [comment]
@maromatorio You can set the function name with the following format:

```
	// The name of the Lambda function.
	//
	// Name formats
	//
	//    * Function name - my-function.
	//
	//    * Function ARN - arn:aws:lambda:us-west-2:123456789012:function:my-function.
	//
	//    * Partial ARN - 123456789012:function:my-function.
	//
	// The length constraint applies only to the full ARN. If you specify only the
	// function name, it is limited to 64 characters in length.
	//
```

see the reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html
