### ISSUE TITLE
New build is making deployments fail

### ISSUE THREAD

**Issue by ryanhuff** [appleboy/lambda-action#36]
I'm guessing you know this since I see failed tests on this repo 3 hours ago, but I'm getting failed deployments... I don't get much in the way of detail to share...

**Comment by suiteappdev** [comment]
![image](https://user-images.githubusercontent.com/5513786/126821209-61d3b145-d38a-4950-8bf1-8036ef56b3b2.png)
I am having issue  with ValidationError status 400

**Comment by denver1117** [comment]
I have the same issue. Lot of my team's deployments are blocked by this. Can this change be rolled back or resolved?

**Comment by suiteappdev** [comment]
@denver1117 waiting for solution. not resolved yet.

**Comment by ryanhuff** [comment]
@denver1117 I think your GitHub action YAML file can specify a version to use... Haven't tried it yet.

**Comment by denver1117** [comment]
> @denver1117 I think your GitHub action YAML file can specify a version to use... Haven't tried it yet.

Nice thanks, we've got some workarounds but will try that as well.

**Comment by aleon68** [comment]
> 
> 
> @denver1117 I think your GitHub action YAML file can specify a version to use... Haven't tried it yet.

how can do it?

**Comment by aleon68** [comment]
> 
> 
> @denver1117 I think your GitHub action YAML file can specify a version to use... Haven't tried it yet.

I found how to do it, great solution!!!!

**Comment by suiteappdev** [comment]
Please  @aleon68  can share the code snipped or you yml file ? please.

**Comment by PascalUlor** [comment]
Whats the fix for this please. My deployments are still failing

**Comment by PascalUlor** [comment]
I've figured it out. Thanks @ryanhuff 
@suiteappdev you need to do this
`appleboy/lambda-action@v0.1.3`
you can pick what ever version you want

**Comment by suiteappdev** [comment]
@PascalUlor thank you deployment is working now.

**Comment by robbylucia** [comment]
This broke my stuff!

**Comment by adamthewan** [comment]
@PascalUlor 's suggestion fixed our deployments

**Comment by Voice-First-AI** [comment]
thank you so much @PascalUlor 🎉😊 you fixed my issues! Pipeline works fine now.

<img width="1425" alt="Screen Shot 2021-07-27 at 1 00 30 PM" src="https://user-images.githubusercontent.com/40079313/127103520-3596ae2f-4885-4749-b5d8-4d76c7a06b3b.png">

**Comment by nerychucuy** [comment]
@PascalUlor 's fix worked for me too.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
I make a new version v0.1.5 to fix the issue.
