### ISSUE TITLE
ValidationException

### ISSUE THREAD

**Issue by pktippa** [appleboy/lambda-action#38]
```
2021/07/30 05:29:58 ValidationException: 
	status code: 400, request id: 56456bc0-3439-4ed9-a1c8-2ada03328dc8
```

Getting validation exception while trying to deploy a lambda function using github action.

**Comment by marchof** [comment]
I can confirm, I get the same error since e66d14057f60ac6acba3e2fedd7d7ab608b84d3f

**Comment by okabhaif** [comment]
There is another issue thread [#36](https://github.com/appleboy/lambda-action/issues/36) for this. 

The thread has a workaround for the issue, my lambda deployments are still failing, but it might help you guys though!

**Comment by bishopandco** [comment]
Same issues here going to try #36

**Comment by pktippa** [comment]
@PascalUlor fix https://github.com/appleboy/lambda-action/issues/36#issuecomment-885985601 worked for me.

**Comment by appleboy** [comment]
I make a new version v0.1.5 to fix the issue.
