### ISSUE TITLE
Does this Action update the python environment from requirements.txt?

### ISSUE THREAD

**Issue by jgwinner** [appleboy/lambda-action#40]
Hello:

The best of the Lambda's updaters, the only one I've seen that request python version.

A question though - will this install a virtual environment from requirements.txt and upload that inside the .zip file?

It wasn't clear from the docs.

**Comment by jgwinner** [comment]
Ah, after running it, it looks like although the key python3.6 can be loaded, it's really just uploading whatever .zip file is in the artifact, not making it, itself.

**Comment by w0rldart** [comment]
@jgwinner what are you using then to process the requirements?
