### ISSUE TITLE
An update is in progress for resource

### ISSUE THREAD

**Issue by ErizonEE** [appleboy/lambda-action#41]
Hi Team, 

We have problems updating lambda with environment vars, we got next message: 

"The operation cannot be performed at this time. An update is in progress for resource: xxxx".

When we comment environment var definition, action work fine.

**Comment by merzikain** [comment]
Having the same problem, is nothing being done about this?

**Comment by rafistrauss** [comment]
#46 has more info about this same issue

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/lambda-action/releases/tag/v0.1.6
