### ISSUE TITLE
Layers are not working

### ISSUE THREAD

**Issue by danielgomezrico** [appleboy/lambda-action#45]
1. If you specify `layers` it does nothing.
2. If I create the layer by hand in the dashboard after I run it I get the error:
```
The operation cannot be performed at this time. An update is in progress for resource
Type: "User"
```

Related to: https://github.com/appleboy/lambda-action/issues/29

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/lambda-action/releases/tag/v0.1.6
