### ISSUE TITLE
ResourceNotReady: exceeded wait attempts

### ISSUE THREAD

**Issue by Jademalo** [appleboy/lambda-action#71]
Not exactly sure why this error is occuring, no configuration has changed since my last deploy which was 2022/12/10. 

Here's a link to the failing log - https://github.com/Jademalo/JadeBots/actions/runs/6699296964/job/18203172897#step:7:26

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
See https://github.com/appleboy/lambda-action#aws-policy

**Comment by Jademalo** [comment]
Thanks, I can confirm that updating the access from

```json
      "Action": [
        "s3:PutObject",
        "iam:ListRoles",
        "lambda:UpdateFunctionCode",
        "lambda:CreateFunction",
        "lambda:UpdateFunctionConfiguration"
      ],
```
to
```json
      "Action": [
        "s3:PutObject",
        "iam:ListRoles",
        "lambda:UpdateFunctionCode",
        "lambda:CreateFunction",
        "lambda:GetFunction",
        "lambda:UpdateFunctionConfiguration",
        "lambda:GetFunctionConfiguration"
      ],
```
has solved this issue. Apologies for the issue, I hadn't realised there had been a breaking change.

Thanks!
