### ISSUE TITLE
How I can give VpcConfig, subnets and securitygroups 

### ISSUE THREAD

**Issue by Minu2020** [appleboy/lambda-action#76]
I am not able to find the correct syntax to add VPC configuration.. Is it supported

**Comment by Minu2020** [comment]
@appleboy any update ?

**Comment by Minu2020** [comment]
Any update @appleboy

**Comment by appleboy** [comment]
@Minu2020  Let me check.

**Comment by appleboy** [comment]
@Minu2020 See https://github.com/appleboy/lambda-action/blob/53c0ab6c9aa0447ba09417d3a601cb55a5ffd05d/action.yml#L55-L58

**Comment by Minu2020** [comment]
@appleboy  I got the following error and that why I opened the issue
![Uploading Screenshot 2024-04-22 at 2.00.20 pm.png…]()

**Comment by Minu2020** [comment]
![Screenshot 2024-04-22 at 2 00 20 pm](https://github.com/appleboy/lambda-action/assets/63351344/46fd9475-7533-4267-9cec-75847ff7a96a)

**Comment by appleboy** [comment]
@Minu2020 Please provide source config.

**Comment by Minu2020** [comment]
@appleboy 

Attached source config..
![Screenshot 2024-06-11 at 1 33 27 pm](https://github.com/appleboy/lambda-action/assets/63351344/5dbc4dbc-6cd6-48bc-b067-f22bc6930157)
![Screenshot 2024-06-11 at 1 28 52 pm](https://github.com/appleboy/lambda-action/assets/63351344/4a943f86-0ec3-455a-9162-038b3bf40a55)

Please help me to find whats wrong
